### ISSUE TITLE
Problems with code compilation

### ISSUE THREAD

**Issue by khozzy** [m4saka/xcs-xcsr#6]
When trying to compile code:
```
$ make

[...]

src/XCSR/../XCS/ga.h:85:41: error: no viable overloaded '='
                        cl.condition[i] = situation.at(i);
                        ~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~
[...]

1 warning and 2 errors generated.
make: *** [xcs] Error 1
```
My G++ version
```
$ g++ --version

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by m4saka** [comment]
It cannot be reproduced by my clang++ on Ubuntu 18.04, and maybe it is a problem specific to clang (g++) for MacOS.
I fixed some implicit cast, but I don't know whether the problem is solved because I don't have Mac.

Could you please try compiling again and give me a feedback?

**Comment by khozzy** [comment]
Thanks, that seems to solve the issue. I'm now able to compile the code gracefully.

**Comment by m4saka** [comment]
Thanks for the feedback!
